name: Certificate Automation Request
description: Request DNS additions for gateway/certificate automation
title: "[Cert Automation] <request-number> - <environment>"
labels:
  - automation
  - certificates
body:
  - type: input
    id: request_number
    attributes:
      label: Request Number
      description: Tracking/request number for this change.
      placeholder: "REQ-12345"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment Name
      description: Environment name (e.g. dev, qa, prod).
      placeholder: "prod"
    validations:
      required: true
  - type: textarea
    id: namespace_dns_mappings
    attributes:
      label: Namespace and DNS Names
      description: Provide each namespace followed by the DNS names for that namespace. Repeat for additional namespaces.
      placeholder: |-
        namespace: platform-scope
        dns:
          - example01.platform-scope.pod.cac.corp.aks.sunlife.com
          - example02.platform-scope.pod.cac.corp.aks.sunlife.com

        namespace: pie-grafana
        dns:
          - example01.pie-grafana.pod.cac.corp.aks.sunlife.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        After creating the issue, add a comment with:
        `/create-PR-DNS`
        This will trigger the automation workflow.
