apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: tenant-cloud-platforms-allow-all
  namespace: cloud-platforms-system
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      istio: cloud-platforms-ingressgateway
